[2024-05-26T08:29:51.385+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_dag.ensure_bucket_task scheduled__2024-05-26T08:26:00+00:00 [queued]>
[2024-05-26T08:29:51.390+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_dag.ensure_bucket_task scheduled__2024-05-26T08:26:00+00:00 [queued]>
[2024-05-26T08:29:51.390+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-26T08:29:51.395+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ensure_bucket_task> on 2024-05-26 08:26:00+00:00
[2024-05-26T08:29:51.402+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-05-26T08:29:51.404+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_dag', 'ensure_bucket_task', 'scheduled__2024-05-26T08:26:00+00:00', '--job-id', '2251', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_store_dag.py', '--cfg-path', '/tmp/tmpovdlx_90']
[2024-05-26T08:29:51.405+0000] {standard_task_runner.py:88} INFO - Job 2251: Subtask ensure_bucket_task
[2024-05-26T08:29:51.412+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-26T08:29:51.429+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_and_store_dag.ensure_bucket_task scheduled__2024-05-26T08:26:00+00:00 [running]> on host d904a9488f34
[2024-05-26T08:29:51.467+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_dag' AIRFLOW_CTX_TASK_ID='ensure_bucket_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T08:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-26T08:26:00+00:00'
[2024-05-26T08:29:51.468+0000] {fetch_and_store_dag.py:29} INFO - Ensuring MinIO bucket exists...
[2024-05-26T08:29:51.470+0000] {fetch_and_store_dag.py:35} INFO - Bucket already exists: mediae
[2024-05-26T08:29:51.471+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-26T08:29:51.475+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_dag, task_id=ensure_bucket_task, execution_date=20240526T082600, start_date=20240526T082951, end_date=20240526T082951
[2024-05-26T08:29:51.496+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-26T08:29:51.509+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
